### ISSUE TITLE
Example playbook not working

### ISSUE THREAD

**Issue by alexanderjardim** [azavea/ansible-hdfs#8]
Using code from the right branch:  
>~/dev/ansible-hdfs/examples> git remote -v 
>origin	https://github.com/azavea/ansible-hdfs.git (fetch)
>origin	https://github.com/azavea/ansible-hdfs.git (push)

And it is up-to-date
>~/dev/ansible-hdfs/examples> git status
>On branch develop
>Your branch is up-to-date with 'origin/develop'.
>nothing to commit, working directory clean

vagrant up breaks
>~/dev/ansible-hdfs/examples> vagrant up
>Bringing machine 'default' up with 'virtualbox' provider...
>==> default: Importing base box 'ubuntu/trusty64'...
>==> default: Matching MAC address for NAT networking...
>==> default: Checking if box 'ubuntu/trusty64' is up to date...
>==> default: Setting the name of the VM: examples_default_1425502066892_3479
>==> default: Clearing any previously set forwarded ports...
>==> default: Clearing any previously set network interfaces...
>==> default: Preparing network interfaces based on configuration...
>    default: Adapter 1: nat
>==> default: Forwarding ports...
>    default: 50070 => 50070 (adapter 1)
>    default: 22 => 2222 (adapter 1)
>==> default: Booting VM...
>==> default: Waiting for machine to boot. This may take a few minutes...
>    default: SSH address: 127.0.0.1:2222
>    default: SSH username: vagrant
>    default: SSH auth method: private key
>    default: Warning: Connection timeout. Retrying...
>    default: Warning: Remote connection disconnect. Retrying...
>==> default: Machine booted and ready!
>==> default: Checking for guest additions in VM...
>==> default: Mounting shared folders...
>    default: /vagrant => /Users/alexanderjardim/dev/ansible-hdfs/examples
>==> default: Running provisioner: ansible...
>
>PLAY [all] ********************************************************************
>
>GATHERING FACTS ***************************************************************
>ok: [default]
>
TASK: [Update APT cache] ******************************************************
>ok: [default]
>
>TASK: [azavea.java | Install OpenJDK JRE (headless)] **************************
>changed: [default]
>
>TASK: [azavea.java | Install OpenJDK JRE] *************************************
>changed: [default]
>
>TASK: [azavea.java | Install OpenJDK] *****************************************
>changed: [default]
>
>TASK: [azavea.java | Set OpenJDK as the default] ******************************
>ok: [default]
>
>TASK: [azavea.java | Configure the WebUpd8 repository] ************************
>skipping: [default]
>
>TASK: [azavea.java | Accept Oracle license] ***********************************
>skipping: [default]
>
>TASK: [azavea.java | Install Oracle Java] *************************************
>skipping: [default]
>
>TASK: [azavea.java | Set Oracle Java as the default] **************************
>skipping: [default]
>
>TASK: [azavea.hdfs | Configure Cloudera APT key] ******************************
>changed: [default]
>
>TASK: [azavea.hdfs | Configure the Cloudera APT repositories] *****************
>changed: [default]
>
>TASK: [azavea.hdfs | Pin Cloudera APT repositories] ***************************
>changed: [default]
>
>TASK: [azavea.hdfs | Install Hadoop HDFS NameNode] ****************************
>failed: [default] => {"failed": true}
>msg: pkgname wildcard and version can not be mixed
>
>FATAL: all hosts have already failed -- aborting
>
>PLAY RECAP ********************************************************************
>           to retry, use: --limit @/Users/alexanderjardim/site.retry
>
>default                    : ok=9    changed=6    unreachable=0    failed=1
>
>Ansible failed to complete successfully. Any error output should be
>visible above. Please fix these errors and try again.

**Comment by notthatbreezy** [comment]
The error `msg: pkgname wildcard and version can not be mixed` has happened in the past for older versions of Ansible - package wildcards were a recent introduction.

Could you verify using the command `ansible --version` that you are using at least `1.8` - that's the minimum Ansible version this playbook supports.

**Comment by notthatbreezy** [comment]
@alexanderjardim has this issue been resolved?
